# Firmware Updater Configuration - ESP32 CH340 OPTIMIZED

target_device:
  vid: "1a86"
  pid: "7523"
  name: "ESP32 with CH340"
  description: "ESP32 Development Board with CH340 USB-Serial"

firmware:
  path: "./firmware/esp32/Blink.ino.bin"
  tool: "esptool.py"
  # OPTIMIZED COMMAND: Lower baudrate, auto reset
  command: "esptool.py --chip esp32 --port {port} --baud {baudrate} --before default_reset --after hard_reset write_flash -z 0x10000 {firmware}"
  baudrate: 115200  # Slower but more stable
  timeout: 180      # Longer timeout
  retry_count: 3
  retry_delay: 5

gpio:
  led_green: 17
  led_yellow: 27
  led_red: 22

logging:
  level: "INFO"
  file: "./logs/app.log"